name: Main Branch Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Test, Lint, and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v2

      - name: Install dependencies
        run: dart pub get

      - name: Run lint
        run: dart analyze

      - name: Run tests with coverage
        run: dart test --coverage=coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Release application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(grep version: pubspec.yaml | awk '{print $2}' | sed 's/ //g' | sed 's/\"//g')
          NEXT_VERSION=$(echo "$VERSION + 0.1" | bc)
          sed -i "s/version: $VERSION/version: $NEXT_VERSION/" pubspec.yaml
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Bump version to $NEXT_VERSION"
          git tag -a "v$NEXT_VERSION" -m "Release v$NEXT_VERSION"
          git push origin main --follow-tags

      - name: Release to App Store and Play Store
        uses: fastlane/fastlane-action@v2
        with:
          lane: release
          app_identifier: "your.app.identifier"
          google_play_track: "internal" # or "alpha", "beta", "production" depending on your track
        env:
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
