name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release new APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Display SERVICE_ACCOUNT_JSON
        run: echo "${{ secrets.SERVICE_ACCOUNT_JSON }}"

      - name: Prepare Google Application Credentials
        shell: bash
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_KEY_SECRET_NAME }}" | base64 --decode > google-application-credentials.json

      - name: Find APK
        run: |
          find . -type f -name '*.apk'

      - name: Deploy to Google Play Console
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.example.flutter_github_actions
          releaseFiles: ./build/app/outputs/flutter-apk/app-release.apk
          track: internal


      - name: Remove credentials file
        if: success() || failure()
        run: |
          rm google-application-credentials.json
